services:
  # 自动更新容器
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 128m
    cpus: 0.25
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  # 家庭自动化平台
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/homeassistant:/config
      - /run/dbus:/run/dbus:ro
    network_mode: host

  # 媒体服务器（开心版）
  emby:
    image: xinjiawei1/emby_unlockd:latest
    container_name: emby
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /opt/emby/config:/config
      - /opt/emby/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
    restart: always

  # 动态 DNS 服务        
  ddns-go:
    image: jeessy/ddns-go
    container_name: ddns-go
    restart: always
    network_mode: host
    volumes:
      - /opt/ddns-go:/root

  # 文件快递柜
  filecodebox:
    image: lanol/filecodebox:latest
    container_name: filecodebox
    restart: always
    ports:
      - 12345:12345
    volumes:
      - /opt/FileCodeBox:/app/data
    environment:
      - TZ=Asia/Shanghai

  # 内网穿透服务（客户端）
  frpc:
    image: snowdreamtech/frpc
    container_name: frpc
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/frpc:/etc/frp
  
  # 内网穿透服务（服务端）
  frps:
    image: snowdreamtech/frps
    container_name: frps
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/frps:/etc/frp

  # PDF 转换服务
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - "8081:8080"
    volumes:
      - /opt/StirlingPDF/trainingData:/usr/share/tessdata
      - /opt/StirlingPDF/extraConfigs:/configs
      - /opt/StirlingPDF/customFiles:/customFiles/
      - /opt/StirlingPDF/logs:/logs/
      - /opt/StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=zh_CN
      - TZ=Asia/Shanghai
    restart: always

  # 免费电影
  libretv:
    image: bestzwei/libretv:latest
    container_name: libretv
    ports:
      - "8899:8080"
    restart: always
    environment:
      - TZ=Asia/Shanghai

  # 导航页
  sun-panel:
    image: hslr/sun-panel:latest
    container_name: sun-panel
    ports:
      - "3002:3002"
    volumes:
      - /opt/sun-panel/conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - TZ=Asia/Shanghai

  # 异地组网服务
  tailscaled:
    image: tailscale/tailscale
    container_name: tailscaled
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTHKEY=tskey-auth-k68eNkeSyz11CNTRL-LcAE9LYDCP # 替换为你的 Tailscale Auth Key
      - TZ=Asia/Shanghai

  # 国家电网数据应用（对接Home Assistant）
  sgcc_electricity_app:
    env_file:
      - sgcc_electricity_new/.env
    image: registry.cn-hangzhou.aliyuncs.com/arcw/sgcc_electricity:latest
    container_name: sgcc_electricity
    network_mode: "host"
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    restart: always
    volumes:
      - ./:/data
    command: python3 main.py
    init: true

  # 肥羊IPTV
  allinone:
    image: youshandefeiyang/allinone
    container_name: allinone
    restart: always
    privileged: true
    ports:
      - "35455:35455"
    command: -tv=true -aesKey=h28xum0q20d5qa39ir5u3glz3xdadlhn -userid=464569852 -token=a57e4b742d040e3a41f993c9dc22c5ceafdad5f1daeff6e771deaf24ec490a331aafdf2476dcfb587dd19d3dd9f859d4b3f91d599fb1b54b530d50c27629f4fb1f84f6d8a26b
 
  # 多种网盘挂载系统
  openlist:
    image: openlistteam/openlist:latest-aio
    container_name: openlist
    restart: always
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - /opt/openlist:/opt/openlist/data

  # 京东签到服务
  jd_sign:
    image: yanyu.icu/yanyuwangluo/jd-sign:latest
    container_name: jd_sign
    restart: always
    ports:
      - "17840:17840"

  # 京东 H5 签名服务
  jd_server:
    image: docker.kfcvme50.tech/zhx47/jd_h5st_server:latest
    container_name: jd_server
    restart: always
    ports:
      - "3001:3001"
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: "50m"

  # 青龙面板
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    hostname: qinglong
    restart: always
    ports:
      - "5700:5700"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/ql/data:/ql/data

  # 远程桌面服务API
  rustdesk:
    image: lejianwen/rustdesk-server-s6:latest
    environment:
      - RELAY=xxx.com:21117 # 替换为你的中继服务器地址
      - ENCRYPTED_ONLY=1
      - MUST_LOGIN=N
      - TZ=Asia/Shanghai
      - ALWAYS_USE_RELAY=N
      - RUSTDESK_API_RUSTDESK_ID_SERVER=xxx.com:21116 # 替换为你的ID服务器地址
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=xxx:21117 # 替换为你的中继服务器地址
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://xxx.com # 替换为你的API服务器地址
      - RUSTDESK_API_KEY_FILE=/data/id_ed25519.pub
      - RUSTDESK_API_JWT_KEY=/data/id_ed25519
    volumes:
      - /opt/rustdesk/server:/data
      - /opt/rustdesk/api:/app/data
    network_mode: "host"
    restart: always 

  # 微软365 E5续订脚本
  ms365:
    image: hanhongyong/ms365-e5-renew-x:general
    container_name: ms365
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "1066:1066"
    restart: always    

  # IT工具箱
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    environment:
      - TZ=Asia/Shanghai
    restart: always
    ports:
      - "8082:80"

  # 音乐服务器
  navidrome:
    image: deluan/navidrome:latest    
    container_name: navidrome
    ports:
      - "4533:4533"
    restart: always 
    environment:   
      - TZ=Asia/Shanghai
      - ND_DEFAULTLANGUAGE=zh-Hans
      - ND_LOGLEVEL=info
      - ND_ENABLESHARING=true
      - ND_SCANSCHEDULE=0
      - ND_BASEURL=
      - ND_PLAYLISTSPATH=.
      - ND_LASTFM_LANGUAGE=zh
      - ND_LASTFM_APIKEY=d3f69254a30d704fb37d5e5c9a39c409
      - ND_LASTFM_SECRET=027ae630f90ce5c06d1d6ce8d8e4d74f
      - ND_SPOTIFY_ID=b4db885f5ce7452ea3d66df3a1ba1158
      - ND_SPOTIFY_SECRET=0b931c3f86c54342a9e878ad8b5d0ca0
      - ND_ENABLEARTWORKPRECACHE=true
    volumes:
      - "/opt/navidrom/data:/data"
      - "/opt/navidrom/music:/music:ro"

  # Nginx 代理服务器
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/nginx/html:/usr/share/nginx/html
      - /opt/nginx/conf.d:/etc/nginx/conf.d 
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/nginx/log:/var/log/nginx
