services:
  # 自动更新容器
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 128m
    cpus: 0.25
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  # 家庭自动化平台（8123）
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/homeassistant:/config
      - /run/dbus:/run/dbus:ro
    network_mode: host

  # 媒体服务器（8096、8920）
  emby:
    image: xinjiawei1/emby_unlockd:latest
    container_name: emby
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /opt/emby/config:/config
      - /opt/emby/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped

  # 动态 DNS 服务（9876） 
  ddns-go:
    image: jeessy/ddns-go
    container_name: ddns-go
    restart: unless-stopped
    ports:
      - 9876:9876
    environment:
      - TZ=Asia/Shanghai    
    volumes:
      - /opt/ddns-go:/root

  # 文件快递柜（12345）
  filecodebox:
    image: lanol/filecodebox:latest
    container_name: filecodebox
    restart: unless-stopped
    ports:
      - 12345:12345
    volumes:
      - /opt/FileCodeBox:/app/data
    environment:
      - TZ=Asia/Shanghai

  # 内网穿透服务（客户端）
  frpc:
    image: snowdreamtech/frpc
    container_name: frpc
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/frpc:/etc/frp
  
  # 内网穿透服务（服务端）
  frps:
    image: snowdreamtech/frps
    container_name: frps
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/frps:/etc/frp

  # PDF 转换服务（8081）
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - "8081:8080"
    volumes:
      - /opt/StirlingPDF/trainingData:/usr/share/tessdata
      - /opt/StirlingPDF/extraConfigs:/configs
      - /opt/StirlingPDF/customFiles:/customFiles/
      - /opt/StirlingPDF/logs:/logs/
      - /opt/StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=zh_CN
      - TZ=Asia/Shanghai
    restart: unless-stopped

  # 免费电影（8899）
  libretv:
    image: bestzwei/libretv:latest
    container_name: libretv
    ports:
      - "8899:8080"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai

  # Stremio 媒体播放器（8084、11470、12470）
  stremio:
    container_name: stremio-docker
    image: tsaridas/stremio-docker:latest
    environment:
      - NO_CORS=1
      - TZ=Asia/Shanghai
    volumes:
      - /opt/stremio-server:/root/.stremio-server
    # devices:
    #  - "/dev/dri/card0:/dev/dri/card0"       # 如果需要硬件加速，可以取消注释
    #  - "/dev/dri/renderD128:/dev/dri/renderD128" # 如果需要硬件加速，可以取消注释
    ports:
      - "8084:8080"
      - "11470:11470"
      - "12470:12470"
    restart: unless-stopped

  # 导航页（3002）
  sun-panel:
    image: hslr/sun-panel:latest
    container_name: sun-panel
    ports:
      - "3002:3002"
    volumes:
      - /opt/sun-panel/conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai

  # 异地组网服务
  tailscaled:
    image: tailscale/tailscale
    container_name: tailscaled
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTHKEY=tskey-auth-k68eNkeSyz11CNTRL-LcAE9LYDCP # 替换为你的 Tailscale Auth Key
      - TZ=Asia/Shanghai

  # 肥羊IPTV（35455）
  allinone:
    image: youshandefeiyang/allinone
    container_name: allinone
    restart: unless-stopped
    privileged: true
    ports:
      - "35455:35455"
    command: -tv=true -aesKey=h28xum0q20d5qa39ir5u3glz3xdadlhn -userid=464569852 -token=a57e4b742d040e3a41f993c9dc22c5ceafdad5f1daeff6e771deaf24ec490a331aafdf2476dcfb587dd19d3dd9f859d4b3f91d599fb1b54b530d50c27629f4fb1f84f6d8a26b
 
  # 支持多存储的文件列表程序（5244）
  openlist:
    image: openlistteam/openlist:latest-aio
    container_name: openlist
    restart: unless-stopped
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - /opt/openlist:/opt/openlist/data

  # 自建京东本地签名服务（17840）
  jd_sign:
    image: yanyu.icu/yanyuwangluo/jd-sign:latest
    container_name: jd_sign
    restart: unless-stopped
    ports:
      - "17840:17840"

  # 自建京东H5算法服务（3001）
  jd_server:
    image: docker.kfcvme50.tech/zhx47/jd_h5st_server:latest
    container_name: jd_server
    restart: unless-stopped
    ports:
      - "3001:3001"
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: "50m"

  # 青龙面板（5700）
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    hostname: qinglong
    restart: unless-stopped
    ports:
      - "5700:5700"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/ql/data:/ql/data

  # 远程桌面服务API
  rustdesk:
    image: lejianwen/rustdesk-server-s6:latest
    environment:
      - RELAY=xxx.com:21117 # 替换为你的中继服务器地址
      - ENCRYPTED_ONLY=1
      - MUST_LOGIN=N
      - TZ=Asia/Shanghai
      - unless-stopped_USE_RELAY=N
      - RUSTDESK_API_RUSTDESK_ID_SERVER=xxx.com:21116 # 替换为你的ID服务器地址
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=xxx:21117 # 替换为你的中继服务器地址
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://xxx.com # 替换为你的API服务器地址
      - RUSTDESK_API_KEY_FILE=/data/id_ed25519.pub
      - RUSTDESK_API_JWT_KEY=/data/id_ed25519
    volumes:
      - /opt/rustdesk/server:/data
      - /opt/rustdesk/api:/app/data
    network_mode: "host"
    restart: unless-stopped 

  # 微软365 E5续订脚本（1066）
  ms365:
    image: hanhongyong/ms365-e5-renew-x:general
    container_name: ms365
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "1066:1066"
    restart: unless-stopped    

  # IT工具箱（8082）
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    ports:
      - "8082:80"

  # n8n 工作流自动化工具（5678）
  n8n:
    container_name: n8n
    image: n8nio/n8n
    environment:      
      - TZ=Asia/Shanghai
      - N8N_SECURE_COOKIE=false
    volumes:
      - /opt/n8n:/home/node/.n8n
    ports:
      - "5678:5678"
    restart: unless-stopped

  # AI视频生成工具（8501、8080）
  moneyprinterturbo:
    image: ghcr.io/e5sub/moneyprinterturbo:latest
    container_name: "moneyprinterturbo"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8501:8501" 
      - "8080:8080"
    volumes:
      - /opt/MoneyPrinterTurbo:/MoneyPrinterTurbo
    restart: unless-stopped
    command: >
      sh -c "
      python3 main.py &
      streamlit run ./webui/Main.py --browser.serverAddress=127.0.0.1 --server.enableCORS=True --browser.gatherUsageStats=False
      "

  # 音乐服务器（4533）
  navidrome:
    image: deluan/navidrome:latest    
    container_name: navidrome
    user: "1000:1000"
    ports:
      - "4533:4533"
    restart: unless-stopped 
    environment:   
      - TZ=Asia/Shanghai
      - ND_DEFAULTLANGUAGE=zh-Hans
      - ND_LOGLEVEL=info
      - ND_ENABLESHARING=true
      - ND_SCANSCHEDULE=0
      - ND_BASEURL=
      - ND_PLAYLISTSPATH=.
      - ND_LASTFM_LANGUAGE=zh
      - ND_LASTFM_APIKEY=d3f69254a30d704fb37d5e5c9a39c409
      - ND_LASTFM_SECRET=027ae630f90ce5c06d1d6ce8d8e4d74f
      - ND_SPOTIFY_ID=b4db885f5ce7452ea3d66df3a1ba1158
      - ND_SPOTIFY_SECRET=0b931c3f86c54342a9e878ad8b5d0ca0
      - ND_ENABLEARTWORKPRECACHE=true
      - ND_ENABLETRANSCODINGCONFIG=true 
      - ND_SUBSONICARTISTPARTICIPATIONS=true
      - ND_DEFAULTTHEME=Nord
    volumes:
      - /opt/navidrom/data:/data
      - /opt/navidrom/music:/music:ro

  # 在线笔记工具（5230）
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: unless-stopped
    ports:
      - "5230:5230"
    volumes:
      - /opt/memos/data:/var/opt/memos
    environment:
      - MEMOS_MODE=prod
      - MEMOS_PORT=5230
      - TZ=Asia/Shanghai

  # 远程下载工具（8083、6881）
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /opt/qbittorrent/appdata:/config
      - /opt/qbittorrent/downloads:/downloads 
    ports:
      - 8083:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  # 软硬路由公网神器
  lucky:
    image: gdy666/lucky
    container_name: lucky
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/lucky:/goodluck 

  # 服务器监控工具（3003）
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "3003:3001"
    volumes:
      - /opt/uptime-kuma:/app/data 

  # Nginx 代理服务器（80、443）
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/nginx/html:/usr/share/nginx/html
      - /opt/nginx/conf:/etc/nginx
      - /opt/nginx/log:/var/log/nginx
      
  # jenkins 持续集成工具（8085、50000） 
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8085:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - TZ=Asia/Shanghai
    volumes:
      - /opt/jenkins:/var/jenkins_home   
 
  # gitlab 代码托管平台（10022、10080、10443）
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped 
    privileged: true
    ports:
      - "10022:22"
      - "10080:80"
      - "10443:443"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/gitlab/config:/etc/gitlab
      - /opt/gitlab/logs:/var/log/gitlab
      - /opt/gitlab/data:/var/opt/gitlab

  # Redis 缓存服务（6379）
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"
    volumes:
      - /opt/redis/conf/redis.conf:/etc/redis/redis.conf
      - /opt/redis/data:/data
    command: redis-server /etc/redis/redis.conf

  # MySQL 数据库（3308）
  mysql:
    image: mysql:8.4   # 使用 MySQL 8.4 版本
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password # 替换为你的 MySQL root 密码
      - MYSQL_DATABASE=my_database # 替换为你的数据库名称
      - MYSQL_ROOT_HOST=% # 允许从任何主机连接 
      - TZ=Asia/Shanghai
    ports:
      - "3308:3306"
    volumes:
      - /opt/mysql/data:/var/lib/mysql
      - /opt/mysql/conf:/etc/mysql/conf.d
      - /opt/mysql/log:/var/log/mysql

  # MongoDB 数据库（27017）
  mongodb:
    image: mongo:8.0.10  # 使用 MongoDB 8.0.10 版本
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # 替换为你的 MongoDB root 用户名
      - MONGO_INITDB_ROOT_PASSWORD=root_password # 替换为你的 MongoDB root 密码
      - TZ=Asia/Shanghai
    ports:
      - "27017:27017"
    volumes:  
      - /opt/mongodb/data:/data/db
      - /opt/mongodb/conf:/data/configdb
      - /opt/mongodb/log:/var/log/mongodb

  # PostgreSQL 数据库（5432）
  postgresql:
    image: postgres:17.5     # 使用 PostgreSQL 17.5 版本
    container_name: postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres # 替换为你的 PostgreSQL 用户名
      - POSTGRES_PASSWORD=postgres_password # 替换为你的 PostgreSQL 密码
      - POSTGRES_DB=my_database # 替换为你的数据库名称
      - TZ=Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - /opt/postgresql/data:/var/lib/postgresql/data   
      - /opt/postgresql/conf:/etc/postgresql
      - /opt/postgresql/log:/var/log/postgresql

  # minio对象存储服务（9000、9001）
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /opt/minio/data:/mnt/data
      - /opt/minio/minio:/etc/config.env
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
      - TZ=Asia/Shanghai
    command: server --console-address ":9001"