version: '3'
services:
  sentinel:
    image: bladex/sentinel-dashboard
    container_name: sentinel
    restart: always
    ports: 
      - "8858:8858"
    volumes:
      - /opt/app/sentinel/logs:/root/logs